### ISSUE TITLE
Crash when sharing traces

### ISSUE THREAD

**Issue by stkent** [pedrovgs/Lynx#25]
Library version: 1.6
Android version: 6.0.1

```
Fatal Exception: java.lang.RuntimeException: Failure from system
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1547)
       at android.app.Activity.startActivityForResult(Activity.java:4283)
       at android.app.Activity.startActivityForResult(Activity.java:4230)
       at android.app.Activity.startActivity(Activity.java:4567)
       at android.app.Activity.startActivity(Activity.java:4535)
       at com.github.pedrovgs.lynx.LynxView.shareTraces(LynxView.java:185)
       at com.github.pedrovgs.lynx.presenter.LynxPresenter.onShareButtonClicked(LynxPresenter.java:120)
       at com.github.pedrovgs.lynx.LynxView$3.onClick(LynxView.java:321)
       at android.view.View.performClick(View.java:5702)
       at android.view.View$PerformClick.run(View.java:22546)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by android.os.TransactionTooLargeException: data parcel size 1541076 bytes
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:503)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3130)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1540)
       at android.app.Activity.startActivityForResult(Activity.java:4283)
       at android.app.Activity.startActivityForResult(Activity.java:4230)
       at android.app.Activity.startActivity(Activity.java:4567)
       at android.app.Activity.startActivity(Activity.java:4535)
       at com.github.pedrovgs.lynx.LynxView.shareTraces(LynxView.java:185)
       at com.github.pedrovgs.lynx.presenter.LynxPresenter.onShareButtonClicked(LynxPresenter.java:120)
       at com.github.pedrovgs.lynx.LynxView$3.onClick(LynxView.java:321)
       at android.view.View.performClick(View.java:5702)
       at android.view.View$PerformClick.run(View.java:22546)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by stkent** [comment]
Thanks for the thoughts, @pedrovgs! I'm not familiar enough with the internals of your library to be able to put up a quick fix, and since we only include it in testing versions of our application I probably won't have dedicated time to circle back. Wanted to report it at least :) Cheers!

**Comment by Emeritus-DarranKelinske** [comment]
Getting this too :)
