### ISSUE TITLE
ConcurrentModificationException in notifyNewTraces

### ISSUE THREAD

**Issue by stkent** [pedrovgs/Lynx#26]
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
       at java.util.LinkedList.addAll(LinkedList.java:394)
       at java.util.LinkedList.(LinkedList.java)
       at com.github.pedrovgs.lynx.model.Lynx.notifyNewTraces(Lynx.java:156)
       at com.github.pedrovgs.lynx.model.Lynx.access$000(Lynx.java:35)
       at com.github.pedrovgs.lynx.model.Lynx$1.onTraceRead(Lynx.java:79)
       at com.github.pedrovgs.lynx.model.Logcat.notifyListener(Logcat.java:95)
       at com.github.pedrovgs.lynx.model.Logcat.readLogcat(Logcat.java:85)
       at com.github.pedrovgs.lynx.model.Logcat.run(Logcat.java:70)
```

**Comment by pedrovgs** [comment]
Thanks for reporting @stkent. Can tell me what's the version of the library you are using?

**Comment by stkent** [comment]
Sure thing, this was in v1.6.

**Comment by pedrovgs** [comment]
Thanks :) Right now I'm working on a different project and I'm not sure if I could fix it soon. If someone wants to take a look that'd be great :)
