### ISSUE TITLE
Please update project to the latest renderers version

### ISSUE THREAD

**Issue by ar-g** [pedrovgs/Lynx#28]
I'm getting a crash in such configuration and multidex on.
```
debugCompile 'com.github.pedrovgs:lynx:1.6'
compile 'com.github.pedrovgs:renderers:3.2.0'
```
```
Caused by: java.lang.NoSuchMethodError: No direct method <init>(Landroid/view/LayoutInflater;Lcom/pedrogomez/renderers/RendererBuilder;Lcom/pedrogomez/renderers/AdapteeCollection;)V in class Lcom/pedrogomez/renderers/RendererAdapter; or its super classes (declaration of 'com.pedrogomez.renderers.RendererAdapter' appears in /data/app/com.lalafo.dev-1/base.apk:classes48.dex)
                                                                    at com.github.pedrovgs.lynx.LynxView.initializeRenderers(LynxView.java:279)
                                                                    at com.github.pedrovgs.lynx.LynxView.initializeView(LynxView.java:246)
                                                                    at com.github.pedrovgs.lynx.LynxView.<init>(LynxView.java:89)
                                                                    at com.github.pedrovgs.lynx.LynxView.<init>(LynxView.java:82)
                                                                    at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:414) 
                                                                    at android.app.Activity.setContentView(Activity.java:2414) 
                                                                    at com.github.pedrovgs.lynx.LynxActivity.onCreate(LynxActivity.java:58) 
                                                                    at android.app.Activity.performCreate(Activity.java:6662) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

**Comment by pedrovgs** [comment]
@ar-g could you send a PR with the fix? I'm working on a different project right now and I'm not sure if I'm going to find time soon for fixing this issue.

**Comment by ar-g** [comment]
@pedrovgs ok, I'll send PR during the week
