### ISSUE TITLE
Samsung: Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.emeritus.globalivy/com.github.pedrovgs.lynx.LynxActivity}: android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>

### ISSUE THREAD

**Issue by Emeritus-DarranKelinske** [pedrovgs/Lynx#32]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.emeritus.globalivy/com.github.pedrovgs.lynx.LynxActivity}: android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3168)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3278)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5184)
       at android.app.ActivityThread.access$1100(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6918)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:640)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450)
       at android.app.Activity.setContentView(Activity.java:2366)
       at com.github.pedrovgs.lynx.LynxActivity.onCreate(LynxActivity.java:65)
       at android.app.Activity.performCreate(Activity.java:6575)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3278)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5184)
       at android.app.ActivityThread.access$1100(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6918)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450)
       at android.app.Activity.setContentView(Activity.java:2366)
       at com.github.pedrovgs.lynx.LynxActivity.onCreate(LynxActivity.java:65)
       at android.app.Activity.performCreate(Activity.java:6575)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3278)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5184)
       at android.app.ActivityThread.access$1100(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6918)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by android.view.InflateException: Binary XML file line #78: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:640)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:480)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
       at com.github.pedrovgs.lynx.LynxView.initializeView(LynxView.java:247)
       at com.github.pedrovgs.lynx.LynxView.<init>(LynxView.java:88)
       at com.github.pedrovgs.lynx.LynxView.<init>(LynxView.java:81)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450)
       at android.app.Activity.setContentView(Activity.java:2366)
       at com.github.pedrovgs.lynx.LynxActivity.onCreate(LynxActivity.java:65)
       at android.app.Activity.performCreate(Activity.java:6575)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3278)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5184)
       at android.app.ActivityThread.access$1100(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6918)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:480)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
       at com.github.pedrovgs.lynx.LynxView.initializeView(LynxView.java:247)
       at com.github.pedrovgs.lynx.LynxView.<init>(LynxView.java:88)
       at com.github.pedrovgs.lynx.LynxView.<init>(LynxView.java:81)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450)
       at android.app.Activity.setContentView(Activity.java:2366)
       at com.github.pedrovgs.lynx.LynxActivity.onCreate(LynxActivity.java:65)
       at android.app.Activity.performCreate(Activity.java:6575)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3278)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5184)
       at android.app.ActivityThread.access$1100(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6918)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by android.content.res.Resources$NotFoundException: Resource "android:drawable/APKTOOL_DUMMY_0941" (1080941)  is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=1 r=0x1080941}
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:3993)
       at android.content.res.Resources.loadDrawable(Resources.java:3905)
       at android.content.res.Resources.getDrawable(Resources.java:1977)
       at android.content.res.Resources.getDrawable(Resources.java:1942)
       at android.widget.AbsListView.initAbsListView(AbsListView.java:1245)
       at android.widget.AbsListView.<init>(AbsListView.java:1150)
       at android.widget.ListView.<init>(ListView.java:166)
       at android.widget.ListView.<init>(ListView.java:162)
       at android.widget.ListView.<init>(ListView.java:158)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:480)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
       at com.github.pedrovgs.lynx.LynxView.initializeView(LynxView.java:247)
       at com.github.pedrovgs.lynx.LynxView.<init>(LynxView.java:88)
       at com.github.pedrovgs.lynx.LynxView.<init>(LynxView.java:81)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450)
       at android.app.Activity.setContentView(Activity.java:2366)
       at com.github.pedrovgs.lynx.LynxActivity.onCreate(LynxActivity.java:65)
       at android.app.Activity.performCreate(Activity.java:6575)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3278)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5184)
       at android.app.ActivityThread.access$1100(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6918)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by pedrovgs** [comment]
Hi @Emeritus-DarranKelinske thanks for reporting. Can you provide any steps to reproduce this bug? Can you reproduce it on any Samsung device? What Android OS version are you using? Is your app obfuscated?

**Comment by Emeritus-DarranKelinske** [comment]
I think it happens when rotating the phone while viewing lynx. The OS is 5.1.1 and the device is a Samsung On5. The app has been obfuscated.
